### PR TITLE
Make it work with Browserify

### PR DESCRIPTION
**Pull request by Tobbe**

### CODE REVIEW

**Comment by Tobbe** [comment]
Should I bump the version as well in this PR?

**Comment by carlansley** [comment]
Sure, bump the version, thanks.

**Comment by carlansley** [comment]
Thanks for the PR!

**Comment by Tobbe** [comment]
Thank you for accepting it so quickly :)
Den 30 mar 2016 18:50 skrev "Carl Ansley" notifications@github.com:

**Comment by Tobbe** [comment]
@carlansley I created a tag in my fork, but it seems tags are not included in PRs. Can you please tag a v1.0.4 release so that I can get this new code through npm? Thanks!

**Comment by carlansley** [comment]
Give it a go now, tagged v1.0.5

**Comment by Tobbe** [comment]
Works perfectly, thanks again :+1:

**Pull request merged**
